site_name: Master Sample Site Name

# REPOSITORY: This refers to the info in the top right that can link directly to the repository 
repo_url: https://github.com/squidfunk/mkdocs-material

# THEME: Setting the theme to use
theme:
  # REPOSITORY: This field lets us change the icon of the top right repo_url
  icon:
    repo: fontawesome/brands/github 
  name: material
  logo: _assets/sample-logo.png
  favicon: _assets/sample-favicon.ico
  palette:
    # THEME: Hard coded color and theme
    # scheme: slate     # Dark mode the site

    # THEME: Enabling the dark and light mode  
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"  # Creates a link to the user's system preference for light and dark appearance
      scheme: default
      primary: indigo     # Primary header color
      accent: indigo      # Hoover and highlight color
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"  # Creates a link to the user's system preference for light and dark appearance
      scheme: slate
      primary: teal     # Primary header color
      accent: teal      # Hoover and highlight color
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tracking     # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking
    # NAVIGATION: This one is important it puts top level files as headers in header bar really changes up the flow
    # - navigation.tabs       # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    # - navigation.sections   # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections
    - navigation.expand       # Start all the side bar folders expanded
    - navigation.indexes      # Enables the nav fields that are down below, without this the site generates it based on folder structure https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
    - navigation.top          # Simple back to top navigation button  

# CUSTOMISATION: Allowing for extra javascript or stylesheets
extra_css:
  - _stylesheets/extra.css

# extra_javascript:
#   - javascripts/extra.js

copyright: Copyright &copy;2023 Josh Mooney@MooJuice Games
extra:
  # mkdocs icon lookup: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/josh-mooney-ire/
      name: Personal LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/JoshMooney
      name: Personal Github
    
    - icon: fontawesome/brands/spotify
      link: https://www.google.com
    - icon: fontawesome/brands/instagram
      link: https://www.google.com
    - icon: fontawesome/brands/youtube
      link: https://www.google.com
    - icon: fontawesome/brands/stack-overflow
      link: https://www.google.com
    - icon: fontawesome/brands/reddit
      link: https://www.google.com
    - icon: fontawesome/brands/discord
      link: https://www.google.com
    - icon: octicons/book-16
      link: https://joshmooney.github.io/

# In order to link a page to a section, create a new document with the name index.md in the respective folder, and add it to the beginning of your navigation section
# Note this requires navigation.indexes in the features section, without this the structure is generated by the folder structure of the project
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
nav:
  - Welcome Page: 'index.md'
  - Nested Section:
    - nested-page/index.md
    - nested-page/sample.md
    - 'section-nested-page/index.md'
    - Sample Page: 'section-nested-page/sample.md'
    - Sample Page w/ Hidden Navigation: 'section-nested-page/sample-with-hidden-navigation.md'